language: node_js
node_js:
  - "5.5.0"
  - "5.0.0"
  - "4.2.6"
  - "4.0.0"
  - "0.10"

before_script:
  - "npm install -g codeclimate-test-reporter"
  - "export CODECLIMATE_REPO_TOKEN=e6593141fa56ea98f6cf70667d77d24088893a3eba9c019c3b675378c837097b"

after_success:
  - "codeclimate-test-reporter < coverage/lcov.info"
  
services:
  - redis-server
